services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: patsign-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: patsign-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
